package food.model;

import java.util.Date;

/**
 * Represents Weather.
 * @author Clara Mae Wells
 */
public class Weather {
	protected int weatherKey;
	protected Date weatherDate;
	protected int tempHighInF;
	protected int tempAverageInF;
	protected int tempLowInF;
	protected int humidityHighPercentage;
	protected int humidityAveragePercentage;
	protected int humidityLowPercentage;
	protected int windHighInMph;
	protected int windAverageInMph;
	protected int windGustHighInMph;
	protected double snowFallInInches;
	protected double precipitationInInches;
	protected Events events;
	
	/**
	 * Enumeration of weather events.
	 * @author Clara Mae Wells
	 *
	 */
	public enum Events {
		Rain, Snow, Both, None
	}

	/**
	 * Constructor with all fields, including auto-generated weatherKey, 
	 * for reading records from MySQL.
	 * 
	 * @param weatherKey Weather's synthetic primary key
	 * @param weatherDate date weather recorded
	 * @param tempHighInF high temperature in fahrenheit
	 * @param tempAverageInF average temperature in fahrenheit
	 * @param tempLowInF low temperature in fahrenheit
	 * @param humidityHighPercentage high humidity percentage
	 * @param humidityAveragePercentage average humidity percentage
	 * @param humidityLowPercentage low humidity percentage
	 * @param windHighInMph high wind in miles per hour
	 * @param windAverageInMph  average wind in miles per hour
	 * @param windGustHighInMph high wind gust in miles per hour
	 * @param snowFallInInches snow fall in inches
	 * @param precipitationInInches precipitation in inches
	 * @param events weather events that occurred
	 */
	public Weather(int weatherKey, Date weatherDate, int tempHighInF, int tempAverageInF, int tempLowInF,
			int humidityHighPercentage, int humidityAveragePercentage, int humidityLowPercentage, int windHighInMph,
			int windAverageInMph, int windGustHighInMph, double snowFallInInches, double precipitationInInches,
			Events events) {
		this.weatherKey = weatherKey;
		this.weatherDate = weatherDate;
		this.tempHighInF = tempHighInF;
		this.tempAverageInF = tempAverageInF;
		this.tempLowInF = tempLowInF;
		this.humidityHighPercentage = humidityHighPercentage;
		this.humidityAveragePercentage = humidityAveragePercentage;
		this.humidityLowPercentage = humidityLowPercentage;
		this.windHighInMph = windHighInMph;
		this.windAverageInMph = windAverageInMph;
		this.windGustHighInMph = windGustHighInMph;
		this.snowFallInInches = snowFallInInches;
		this.precipitationInInches = precipitationInInches;
		this.events = events;
	}
	
	/**
	 * Constructor for creating new records when the weatherKey is not yet
	 * assigned since it is auto-generated by MySQL.
	 * 
	 * @param weatherDate date weather recorded
	 * @param tempHighInF high temperature in fahrenheit
	 * @param tempAverageInF average temperature in fahrenheit
	 * @param tempLowInF low temperature in fahrenheit
	 * @param humidityHighPercentage high humidity percentage
	 * @param humidityAveragePercentage average humidity percentage
	 * @param humidityLowPercentage low humidity percentage
	 * @param windHighInMph high wind in miles per hour
	 * @param windAverageInMph  average wind in miles per hour
	 * @param windGustHighInMph high wind gust in miles per hour
	 * @param snowFallInInches snow fall in inches
	 * @param precipitationInInches precipitation in inches
	 * @param events weather events that occurred
	 */
	public Weather(Date weatherDate, int tempHighInF, int tempAverageInF, int tempLowInF,
			int humidityHighPercentage, int humidityAveragePercentage, int humidityLowPercentage, int windHighInMph,
			int windAverageInMph, int windGustHighInMph, double snowFallInInches, double precipitationInInches,
			Events events) {
		this.weatherDate = weatherDate;
		this.tempHighInF = tempHighInF;
		this.tempAverageInF = tempAverageInF;
		this.tempLowInF = tempLowInF;
		this.humidityHighPercentage = humidityHighPercentage;
		this.humidityAveragePercentage = humidityAveragePercentage;
		this.humidityLowPercentage = humidityLowPercentage;
		this.windHighInMph = windHighInMph;
		this.windAverageInMph = windAverageInMph;
		this.windGustHighInMph = windGustHighInMph;
		this.snowFallInInches = snowFallInInches;
		this.precipitationInInches = precipitationInInches;
		this.events = events;
	}
	
	/**
	 * Constructor for reading records from MySQL.
	 * Given the weatherKey primary key, fetch the full Weather record.
	 * 
	 * @param weatherKey Weather's synthetic primary key
	 */
	public Weather(int weatherKey) {
		this.weatherKey = weatherKey;
	}

	/**
	 * @return the weatherKey
	 */
	public int getWeatherKey() {
		return weatherKey;
	}

	/**
	 * @param weatherKey the weatherKey to set
	 */
	public void setWeatherKey(int weatherKey) {
		this.weatherKey = weatherKey;
	}

	/**
	 * @return the weatherDate
	 */
	public Date getWeatherDate() {
		return weatherDate;
	}

	/**
	 * @param weatherDate the weatherDate to set
	 */
	public void setWeatherDate(Date weatherDate) {
		this.weatherDate = weatherDate;
	}

	/**
	 * @return the tempHighInF
	 */
	public int getTempHighInF() {
		return tempHighInF;
	}

	/**
	 * @param tempHighInF the tempHighInF to set
	 */
	public void setTempHighInF(int tempHighInF) {
		this.tempHighInF = tempHighInF;
	}

	/**
	 * @return the tempAverageInF
	 */
	public int getTempAverageInF() {
		return tempAverageInF;
	}

	/**
	 * @param tempAverageInF the tempAverageInF to set
	 */
	public void setTempAverageInF(int tempAverageInF) {
		this.tempAverageInF = tempAverageInF;
	}

	/**
	 * @return the tempLowInF
	 */
	public int getTempLowInF() {
		return tempLowInF;
	}

	/**
	 * @param tempLowInF the tempLowInF to set
	 */
	public void setTempLowInF(int tempLowInF) {
		this.tempLowInF = tempLowInF;
	}

	/**
	 * @return the humidityHighPercentage
	 */
	public int getHumidityHighPercentage() {
		return humidityHighPercentage;
	}

	/**
	 * @param humidityHighPercentage the humidityHighPercentage to set
	 */
	public void setHumidityHighPercentage(int humidityHighPercentage) {
		this.humidityHighPercentage = humidityHighPercentage;
	}

	/**
	 * @return the humidityAveragePercentage
	 */
	public int getHumidityAveragePercentage() {
		return humidityAveragePercentage;
	}

	/**
	 * @param humidityAveragePercentage the humidityAveragePercentage to set
	 */
	public void setHumidityAveragePercentage(int humidityAveragePercentage) {
		this.humidityAveragePercentage = humidityAveragePercentage;
	}

	/**
	 * @return the humidityLowPercentage
	 */
	public int getHumidityLowPercentage() {
		return humidityLowPercentage;
	}

	/**
	 * @param humidityLowPercentage the humidityLowPercentage to set
	 */
	public void setHumidityLowPercentage(int humidityLowPercentage) {
		this.humidityLowPercentage = humidityLowPercentage;
	}

	/**
	 * @return the windHighInMph
	 */
	public int getWindHighInMph() {
		return windHighInMph;
	}

	/**
	 * @param windHighInMph the windHighInMph to set
	 */
	public void setWindHighInMph(int windHighInMph) {
		this.windHighInMph = windHighInMph;
	}

	/**
	 * @return the windAverageInMph
	 */
	public int getWindAverageInMph() {
		return windAverageInMph;
	}

	/**
	 * @param windAverageInMph the windAverageInMph to set
	 */
	public void setWindAverageInMph(int windAverageInMph) {
		this.windAverageInMph = windAverageInMph;
	}

	/**
	 * @return the windGustHighInMph
	 */
	public int getWindGustHighInMph() {
		return windGustHighInMph;
	}

	/**
	 * @param windGustHighInMph the windGustHighInMph to set
	 */
	public void setWindGustHighInMph(int windGustHighInMph) {
		this.windGustHighInMph = windGustHighInMph;
	}

	/**
	 * @return the snowFallInInches
	 */
	public double getSnowFallInInches() {
		return snowFallInInches;
	}

	/**
	 * @param snowFallInInches the snowFallInInches to set
	 */
	public void setSnowFallInInches(double snowFallInInches) {
		this.snowFallInInches = snowFallInInches;
	}

	/**
	 * @return the precipitationInInches
	 */
	public double getPrecipitationInInches() {
		return precipitationInInches;
	}

	/**
	 * @param precipitationInInches the precipitationInInches to set
	 */
	public void setPrecipitationInInches(double precipitationInInches) {
		this.precipitationInInches = precipitationInInches;
	}

	/**
	 * @return the events
	 */
	public Events getEvents() {
		return events;
	}

	/**
	 * @param events the events to set
	 */
	public void setEvents(Events events) {
		this.events = events;
	}
}